# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-forward:
    # Steps represent a sequence of tasks that will be executed as part of the job
    runs-on: ubuntu-latest
    container: slaclab/larndsim:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Check forward
        run: |
          pytest tests/test_forward.py

      - name: Archive test output
        uses: actions/upload-artifact@v4
        with:
          name: forward-test-output
          path: tests/output/forward-test-output.pth 

  test-backward:
    # Steps represent a sequence of tasks that will be executed as part of the job
    runs-on: ubuntu-latest
    container: slaclab/larndsim:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Check backward
        run: |
          pytest tests/test_backward.py

      - name: Archive test output
        uses: actions/upload-artifact@v4
        with:
          name: backward-test-output
          path: tests/output/backward-test-output.pkl
